# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAddsalesplan():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_addsalesplan(self):
    self.driver.get("http://124.222.178.125:3006/")
    self.driver.set_window_size(1936, 1056)
    # 点击菜单”Amazon发货“
    self.driver.find_element(By.CSS_SELECTOR, ".ant-menu-submenu-active span > span").click()
    # 点击菜单”销售计划“
    self.driver.find_element(By.LINK_TEXT, "销售计划").click()
    # 点击第二个店铺（需修改为按照店铺名定位）
    self.driver.find_element(By.CSS_SELECTOR, ".ant-tabs:nth-child(1) .ant-tabs-tab:nth-child(2)").click()
    # 点击第一个国家（需改为按照国家名定位）
    self.driver.find_element(By.CSS_SELECTOR, ".country-item:nth-child(1)").click()
    # 点击ASIN查询框
    self.driver.find_element(By.CSS_SELECTOR, ".ant-form-item-children > .ant-input").click()
    # 输入要查询的ASIN
    self.driver.find_element(By.CSS_SELECTOR, ".ant-form-item-children > .ant-input").send_keys("B097BPFD9X")
    # 点击查询按钮
    self.driver.find_element(By.CSS_SELECTOR, ".ant-btn:nth-child(1)").click()
    # 点击”创建需求“
    self.driver.find_element(By.CSS_SELECTOR, ".ant-tooltip-open > .action-jeecg").click()
    # 点击”选择月份“
    self.driver.find_element(By.CSS_SELECTOR, ".ant-col-xs-24 .ant-calendar-picker-input").click()
    # 月份选择”三月“
    self.driver.find_element(By.LINK_TEXT, "三月").click()
    # 点击”输入计划数量“
    self.driver.find_element(By.CSS_SELECTOR, ".ant-input-number-input").click()
    # 计划数量输入”100“
    self.driver.find_element(By.CSS_SELECTOR, ".ant-input-number-input").send_keys("100")
    # 点击”保存并继续“按钮
    self.driver.find_element(By.CSS_SELECTOR, ".ant-modal-footer > .ant-btn:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".has-success .ant-calendar-picker-input").click()
    self.driver.find_element(By.LINK_TEXT, "四月").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ant-input-number-input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ant-input-number-input").send_keys("100")
    self.driver.find_element(By.CSS_SELECTOR, ".ant-modal-footer > .ant-btn:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".has-success .ant-calendar-picker-input").click()
    self.driver.find_element(By.LINK_TEXT, "五月").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ant-input-number-input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ant-input-number-input").send_keys("100")
    self.driver.find_element(By.CSS_SELECTOR, ".ant-modal-footer > .ant-btn:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".has-success .ant-calendar-picker-input").click()
    self.driver.find_element(By.LINK_TEXT, "六月").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ant-input-number-input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ant-input-number-input").send_keys("100")
    # 点击”确认“按钮
    self.driver.find_element(By.CSS_SELECTOR, ".ant-modal-footer > .ant-btn:nth-child(3)").click()
  
