# Generated by Selenium IDE
from webbrowser import Chrome

import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.service import Service


class TestSalesplanadd():
    def setup_method(self, method):
        # 构建chromedriver绝对路径
        from config.config import CHROME_DRIVER_PATH
        driver_path = CHROME_DRIVER_PATH

        # 初始化浏览器实例
        service = Service(str(driver_path))
        driver = Chrome(service=service)

        self.vars = {}

        def teardown_method(self, method):

            self.driver.quit()

    def test_salesplanadd(self):
        self.driver.get("http://192.168.150.222:3066/dashboard/analysis")
        self.driver.set_window_size(1936, 1056)
        self.driver.find_element(By.CSS_SELECTOR, ".ant-menu-submenu-active span > span").click()
        self.driver.find_element(By.LINK_TEXT, "销售计划").click()
        self.driver.find_element(By.CSS_SELECTOR, ".ant-tabs:nth-child(1) .ant-tabs-tab:nth-child(2)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".country-item:nth-child(1)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".ant-tooltip-open > .action-jeecg").click()
        self.driver.find_element(By.CSS_SELECTOR, ".ant-col-xs-24 .ant-calendar-picker-input").click()
        self.driver.find_element(By.LINK_TEXT, "三月").click()
        self.driver.find_element(By.CSS_SELECTOR, ".ant-input-number-input").click()
        self.driver.find_element(By.CSS_SELECTOR, ".ant-input-number-input").send_keys("1000")
        self.driver.find_element(By.CSS_SELECTOR, ".ant-modal-footer > .ant-btn:nth-child(2)").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".ant-modal-footer > .ant-btn:nth-child(2)")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".has-success .ant-calendar-picker-input").click()
        self.driver.find_element(By.LINK_TEXT, "四月").click()
        self.driver.find_element(By.CSS_SELECTOR, ".ant-input-number-input").click()
        self.driver.find_element(By.CSS_SELECTOR, ".ant-input-number-input").send_keys("1000")
        self.driver.find_element(By.CSS_SELECTOR, ".ant-modal-footer > .ant-btn:nth-child(2)").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".ant-modal-footer > .ant-btn:nth-child(2)")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".has-success .ant-calendar-picker-input").click()
        self.driver.find_element(By.LINK_TEXT, "五月").click()
        self.driver.find_element(By.CSS_SELECTOR, ".ant-input-number-input").click()
        self.driver.find_element(By.CSS_SELECTOR, ".ant-input-number-input").send_keys("1000")
        self.driver.find_element(By.CSS_SELECTOR, ".ant-modal-footer > .ant-btn:nth-child(2)").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".ant-modal-footer > .ant-btn:nth-child(2)")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, ".ant-modal-footer > .ant-btn:nth-child(2)")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".has-success .ant-calendar-picker-input").click()
        self.driver.find_element(By.LINK_TEXT, "六月").click()
        self.driver.find_element(By.CSS_SELECTOR, ".ant-input-number-input").click()
        self.driver.find_element(By.CSS_SELECTOR, ".ant-input-number-input").send_keys("1000")
        self.driver.find_element(By.CSS_SELECTOR, ".ant-modal-footer > .ant-btn:nth-child(3)").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".ant-modal-footer > .ant-btn:nth-child(3)")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".vxe-table--body:nth-child(3) .vxe-body--row:nth-child(1) .ant-table-row-expand-icon").click()
